baseURL = '[https://rwgb.github.io/](https://rwgb.github.io/)'
languageCode = 'en-us'
title = 'Arman den | Just a Website'
theme = 'congo'
enableRobotsTXT = true
summaryLength = 30

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[[languages.en.params.author](http://languages.en.params.author/)]
name = "Arman den"
headline = "Developer"
bio = "Building projects..."
