baseURL = '[https://armanden.github.io/](https://armanden.github.io/)'
languageCode = 'en-us'
title = 'Arman den'
theme = 'congo'
enableRobotsTXT = true
summaryLength = 30

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]